name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          #  - read:project
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.readonly }}

          # Options
          user: dingjingmaster
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          base_skip: yes
          config_display: large
          config_octicon: yes
          config_timezone: Asia/Shanghai
          config_twemoji: yes
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_discussions_categories_limit: 100
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          plugin_fortune: yes
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 1000
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_lines_history_limit: 100
          plugin_lines_repositories_limit: 100
          plugin_lines_sections: base
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_self: yes
          plugin_notable_types: commit
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_pwa: yes
          plugin_pagespeed_url: .user.website
          plugin_poopmap: yes
          plugin_poopmap_days: 1000
          plugin_projects: yes
          plugin_projects_descriptions: yes
          plugin_projects_limit: 20
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: chartist
          plugin_stock: yes
          plugin_stock_duration: max
          plugin_stock_interval: 5m
          plugin_support: yes
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_days: 180
          plugin_wakatime_limit: 100
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
          repositories_batch: 1000
          repositories_forks: yes
